name: Generate PlantUML diagrams

on:
  push:
    paths:
      - 'docs/diagrams/**.puml'
      - 'docs/specifications/**'
      - '.github/workflows/plantuml.yml'

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: docs/diagrams/images
          message: "ci: regenerate PlantUML diagrams [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
